name: CI

on: 
  - pull_request
  - workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4.2.2

      - name: Setup micromamba environment
        uses: mamba-org/setup-micromamba@0dea6379afdaffa5d528b3d1dabc45da37f443fc # v2.0.4
        with:
          environment-name: test-env
          create-args: >-
            python=${{ matrix.python-version }}

      - name: Install source
        shell: bash -l {0}
        run: python -m pip install .[dev]

      - name: List installed packages
        shell: bash -l {0}
        run: pip freeze

      - name: Run tests
        shell: bash -l {0}
        run: pytest